host: 0.0.0.0
mysql:
    db: sqlfather
    host: 127.0.0.1
    password: 12345
    port: 3306
    user: root
port: 8102
redis:
    db: 0
    expire_hour: 12
    host: 127.0.0.1
    pool_size: 10
    port: 6379
